### ISSUE TITLE
fix dynarray_get, dynarray_remove

### ISSUE THREAD

**Issue by cwmoreiras** [cwmoreiras/blockchainos#4]
return an error code, and use a pointer to return the buffer

**Comment by CarltonBranch** [comment]
Hi, I've read through this and the code a few times but I want to be clear that I understand what you're asking for before I start. Would you mind explaining it a bit?

**Comment by cwmoreiras** [comment]
Sure! Right now both of these functions return the element that is being removed, and use an argument to give the caller an error code. I think it would be better if they did the opposite: return an error code, and the caller could provide a buffer that the function fills with the element that is being gotten/removed. That should be an easy pull request.

If you want to do more:
The purpose of the dynarray structure is so that blocks can hold a variable amount of data. Right now the dynarray buffer operates on bytes. It might be better to have it operate on a larger data type. Possibly uint32_t. OR it might be better to have it operate on void *, to keep it generic, but that might be more of a risk than what we have to gain from it (operating directly on memory, etc.)
